export const BillActionTypes = {
    SET_CURRENT_BILLS: 'SET_CURRENT_BILLS',
    SET_CURRENT_BILL_MEMBERS: 'SET_CURRENT_BILL_MEMBERS',
    DELETE_MEMBER_FROM_THE_BILL: 'DELETE_MEMBER_FROM_THE_BILL',
    SET_AMOUNT_MEMBER: 'SET_AMOUNT_MEMBER',
    SET_MEMBER_PROCENT: 'SET_MEMBER_PROCENT',
    SET_BILL_AMOUNT: 'SET_BILL_AMOUNT',
    RESET_BILL_MEMBERS: 'RESET_BILL_MEMBERS'
};