export const RoomsActionTypes = {
    SET_CURRENT_ROOMS: 'SET_CURRENT_ROOMS',
    RESET_CURRENT_ROOMS: 'RESET_CURRENT_ROOMS',
    TOGGLE_CREATE_HIDDEN: 'TOGGLE_CREATE_HIDDEN',
    ADD_ONE_ROOM: 'ADD_ONE_ROOM',
    DELETE_ONE_ROOM: 'DELETE_ONE_ROOM'
};